mod "h0tbird/r_base",
    :git  => "https://github.com/h0tbird/puppet.git",
    :path => "roles/r_base"

mod "h0tbird/supervisord",
    :git => "https://github.com/h0tbird/puppet-supervisord.git"

mod "h0tbird/sshd",
    :git => "https://github.com/h0tbird/puppet-sshd.git"
