mod 'r_base',
  :git => 'https://github.com/h0tbird/puppet-r_base.git'

mod 'users',
  :git => 'https://github.com/h0tbird/puppet-users.git'

mod 'hosts',
  :git => 'https://github.com/h0tbird/puppet-hosts.git'

mod 'factsdotd',
  :git => 'https://github.com/h0tbird/puppet-factsdotd.git'

mod 'yum',
  :git => 'https://github.com/h0tbird/puppet-yum.git'

mod 'sshd',
  :git => 'https://github.com/h0tbird/puppet-sshd.git'
